[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[workspace]
resolver = "2"
members = [
	"crates/core",
	"crates/cli",
]

[workspace.dependencies]
anyhow = "1.0.95"

include_dir = "0.7.4"
